const $=id=>document.getElementById(id);let data=[];
document.addEventListener("DOMContentLoaded",()=>{let d=new Date().toISOString().slice(0,10);$("tanggal").value=d;
$("addBtn").onclick=()=>openModal();$("closeBtn").onclick=closeModal;$("cancelBtn").onclick=closeModal;$("form").onsubmit=save;
$("search").oninput=render;$("dateFilter").onchange=render;$("statusFilter").onchange=render;$("refreshBtn").onclick=load;load()});
async function api(action,payload={}){if(!API_URL||API_URL.includes("PASTE_URL"))throw Error("API_URL belum diisi");let r=await fetch(API_URL,{method:"POST",body:JSON.stringify({modul:"jadwal",action,...payload})});let x=await r.json();if(!x.ok)throw Error(x.message);return x}
async function load(){try{data=(await api("list")).data||[];render()}catch(e){data=JSON.parse(localStorage.getItem("jadwal_pekerjaan")||"[]");render();toast("Mode lokal: "+e.message)}}
function render(){let q=$("search").value.toLowerCase(),df=$("dateFilter").value,sf=$("statusFilter").value;
let rows=data.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q)&&(!df||x.tanggal===df)&&(!sf||x.status===sf));
$("body").innerHTML=rows.map(x=>`<tr><td>${esc(x.tanggal)}</td><td>${esc(x.mulai)}${x.selesai?" - "+esc(x.selesai):""}</td><td><b>${esc(x.pekerjaan)}</b><br><span class="small">${esc(x.keterangan||"")}</span></td><td>${esc(x.lokasi)}</td><td>${esc(x.petugas||"-")}</td><td>${esc(x.prioritas)}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td><div class="actions"><button class="btn edit" onclick="edit('${escA(x.id)}')">Edit</button><button class="btn delete" onclick="del('${escA(x.id)}')">Hapus</button></div></td></tr>`).join("");
$("empty").style.display=rows.length?"none":"block";let now=new Date(),today=now.toISOString().slice(0,10),start=new Date(now);start.setDate(now.getDate()-now.getDay()+1);let end=new Date(start);end.setDate(start.getDate()+6);
$("total").textContent=data.length;$("today").textContent=data.filter(x=>x.tanggal===today).length;$("week").textContent=data.filter(x=>{let d=new Date(x.tanggal);return d>=start&&d<=end}).length;$("done").textContent=data.filter(x=>x.status==="Selesai").length}
function openModal(x=null){$("modal").classList.remove("hidden");$("modalTitle").textContent=x?"Edit Jadwal":"Tambah Jadwal";$("id").value=x?.id||"";$("tanggal").value=x?.tanggal||new Date().toISOString().slice(0,10);$("mulai").value=x?.mulai||"08:00";$("selesai").value=x?.selesai||"";$("pekerjaan").value=x?.pekerjaan||"";$("lokasi").value=x?.lokasi||"";$("petugas").value=x?.petugas||"";$("prioritas").value=x?.prioritas||"Normal";$("status").value=x?.status||"Terjadwal";$("keterangan").value=x?.keterangan||""}
function closeModal(){$("modal").classList.add("hidden")}
async function save(e){e.preventDefault();let x={id:$("id").value||"JD-"+Date.now(),tanggal:$("tanggal").value,mulai:$("mulai").value,selesai:$("selesai").value,pekerjaan:$("pekerjaan").value,lokasi:$("lokasi").value,petugas:$("petugas").value,prioritas:$("prioritas").value,status:$("status").value,keterangan:$("keterangan").value};try{await api(data.some(y=>y.id===x.id)?"update":"create",{data:x});toast("Jadwal tersimpan");closeModal();load()}catch(e){let i=data.findIndex(y=>y.id===x.id);i>=0?data[i]=x:data.unshift(x);localStorage.setItem("jadwal_pekerjaan",JSON.stringify(data));render();closeModal();toast("Tersimpan di browser")}}
window.edit=id=>{let x=data.find(y=>y.id===id);if(x)openModal(x)}
window.del=async id=>{if(!confirm("Hapus jadwal ini?"))return;try{await api("delete",{id});load()}catch(e){data=data.filter(x=>x.id!==id);localStorage.setItem("jadwal_pekerjaan",JSON.stringify(data));render();toast("Dihapus dari browser")}}
function toast(s){let t=$("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2500)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function escA(v){return esc(v).replace(/`/g,"&#096;")}
