// ================================================================
// DATABASE KEUANGAN PROYEK MAJU ABADI GROUP
// Tempel seluruh kode ini di Extensions > Apps Script pada Spreadsheet.
// Jalankan setupDatabase() SATU KALI, lalu Deploy > New deployment > Web app.
// Execute as: Me | Who has access: Anyone
// ================================================================
const SHEETS={projects:'PROYEK',payments:'PEMBAYARAN',officials:'PEJABAT',activities:'LOG_AKTIVITAS'};
const HEADERS={
 PROYEK:['id','company','tanggal','noKontrak','nama','opd','lokasi','nilai','pph','ppn','tahun','ppkom','pptk','mandor','staff','keterangan','createdAt','updatedAt'],
 PEMBAYARAN:['id','company','projectId','tanggal','termin','nominal','keterangan','createdAt'],
 PEJABAT:['id','company','nama','nip','jabatan','instansi','createdAt'],
 LOG_AKTIVITAS:['id','waktu','company','aktivitas','data','keterangan']
};
function doGet(e){return json(handle((e&&e.parameter&&e.parameter.action)||'list',e?e.parameter:{}));}
function doPost(e){try{const d=JSON.parse((e.postData&&e.postData.contents)||'{}');return json(handle(d.action||'list',d));}catch(err){return json({ok:false,message:String(err)})}}
function json(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}
function setupDatabase(){Object.keys(HEADERS).forEach(name=>ensureSheet(name,HEADERS[name]));const ss=SpreadsheetApp.getActive();ss.getSheets().forEach(s=>{if(HEADERS[s.getName()]){s.setFrozenRows(1);s.getRange(1,1,1,s.getLastColumn()).setFontWeight('bold').setBackground('#0b66c3').setFontColor('#ffffff');s.autoResizeColumns(1,s.getLastColumn())}});return 'Database siap';}
function ensureSheet(name,headers){const ss=SpreadsheetApp.getActive();let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(s.getLastRow()===0)s.getRange(1,1,1,headers.length).setValues([headers]);else{const old=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];headers.forEach(h=>{if(!old.includes(h)){s.getRange(1,s.getLastColumn()+1).setValue(h);old.push(h)}})}return s}
function handle(action,d){try{setupDatabase();if(action==='list')return {ok:true,projects:read('PROYEK'),payments:read('PEMBAYARAN'),officials:read('PEJABAT'),activities:read('LOG_AKTIVITAS')};if(action==='saveProject'){const existed=findById('PROYEK',d.data.id);d.data.updatedAt=new Date();if(!d.data.createdAt)d.data.createdAt=new Date();const r=upsert('PROYEK',d.data);logActivity(d.data.company,existed?'Edit Proyek':'Proyek Dibuat',d.data.nama,(existed?'Data kontrak diperbarui':'Nilai kontrak '+d.data.nilai));return r}if(action==='savePayment'){d.data.createdAt=new Date();const r=append('PEMBAYARAN',d.data);const p=findById('PROYEK',d.data.projectId);logActivity(d.data.company,'Pembayaran Ditambahkan',p?p.nama:d.data.projectId,(d.data.termin||'Termin')+' • Rp'+Number(d.data.nominal||0).toLocaleString('id-ID'));return r}if(action==='saveOfficial'){d.data.createdAt=new Date();const r=append('PEJABAT',d.data);logActivity(d.data.company,'Pejabat Ditambahkan',d.data.nama,(d.data.jabatan||'')+(d.data.nip?' • NIP '+d.data.nip:''));return r}if(action==='delete'){const old=findById(d.sheet,d.id),r=remove(d.sheet,d.id);if(old)logActivity(old.company,'Hapus Data',old.nama||old.termin||d.sheet,'Data dihapus dari '+d.sheet);return r}if(action==='deleteProject'){const old=findById('PROYEK',d.id);removeChildren('PEMBAYARAN','projectId',d.id);const r=remove('PROYEK',d.id);if(old)logActivity(old.company,'Hapus Proyek',old.nama,'Proyek dan riwayat pembayarannya dihapus');return r}return {ok:false,message:'Action tidak dikenal: '+action};}catch(err){return {ok:false,message:String(err)}}}
function read(name){const s=ensureSheet(name,HEADERS[name]);if(s.getLastRow()<2)return [];const v=s.getDataRange().getDisplayValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=='')).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function append(name,o){const s=ensureSheet(name,HEADERS[name]),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>o[k]??''));return {ok:true}}
function upsert(name,o){const s=ensureSheet(name,HEADERS[name]),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];let i=-1;if(s.getLastRow()>1){const ids=s.getRange(2,1,s.getLastRow()-1,1).getDisplayValues().flat();i=ids.indexOf(String(o.id))}const row=h.map(k=>o[k]??'');if(i<0)s.appendRow(row);else s.getRange(i+2,1,1,h.length).setValues([row]);return {ok:true}}
function remove(name,id){if(!HEADERS[name])throw new Error('Sheet tidak valid');const s=ensureSheet(name,HEADERS[name]);if(s.getLastRow()<2)return {ok:true};const ids=s.getRange(2,1,s.getLastRow()-1,1).getDisplayValues().flat(),i=ids.indexOf(String(id));if(i>=0)s.deleteRow(i+2);return {ok:true}}
function removeChildren(name,key,value){const s=ensureSheet(name,HEADERS[name]);if(s.getLastRow()<2)return;const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0],col=h.indexOf(key)+1;if(!col)return;for(let r=s.getLastRow();r>=2;r--)if(String(s.getRange(r,col).getDisplayValue())===String(value))s.deleteRow(r)}

function findById(name,id){const rows=read(name);return rows.find(x=>String(x.id)===String(id))||null}
function logActivity(company,aktivitas,data,keterangan){append('LOG_AKTIVITAS',{id:Utilities.getUuid(),waktu:Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Jakarta','dd/MM/yyyy HH:mm:ss'),company:company||'',aktivitas:aktivitas||'',data:data||'',keterangan:keterangan||''})}
